using System.ComponentModel;

namespace ContactSystem.DTOs
{
    /// <summary>Contact record returned by the API.</summary>
    public class ContactResponseDto
    {
        /// <summary>Primary key of the contact.</summary>
        [Description("Primary key of the contact (auto-generated by the server).")]
        public int ContactId { get; set; }

        /// <summary>Given / first name of the contact.</summary>
        [Description("Given / first name of the contact.")]
        public string FirstName { get; set; } = string.Empty;

        /// <summary>Family / last name of the contact.</summary>
        [Description("Family / last name of the contact.")]
        public string LastName { get; set; } = string.Empty;

        /// <summary>Country code including the leading '+', e.g. "+91".</summary>
        [Description("Country calling code including the leading '+' (e.g. '+91', '+1', '+971').")]
        public string CountryCode { get; set; } = string.Empty;

        /// <summary>National number without the country code, digits only, e.g. "9087648930".</summary>
        [Description("National / subscriber number without the country code, digits only (e.g. '9087648930').")]
        public string NationalNumber { get; set; } = string.Empty;

        /// <summary>Full phone number, stored as BIGINT (digits only, no '+').</summary>
        /// <remarks>
        /// Server-composed value: <c>CountryCode</c> without '+' concatenated with
        /// <c>NationalNumber</c>, then parsed as <see cref="long"/>. Unique across the
        /// table. e.g. <c>919087648930</c>.
        /// </remarks>
        [Description("Full phone number as an integer. Composed server-side from countryCode + nationalNumber; unique.")]
        public long PhoneNumber { get; set; }

        /// <summary>Id of the project this contact belongs to.</summary>
        [Description("Id of the project this contact belongs to.")]
        public int ProjectId { get; set; }

        /// <summary>Whether the contact is currently opted-in to receive messages.</summary>
        [Description("Whether the contact is currently subscribed (opt-in flag).")]
        public bool IsSubscribed { get; set; }

        /// <summary>UTC timestamp of when the contact was created.</summary>
        [Description("UTC timestamp of when the contact was created (server-generated).")]
        public DateTime CreatedDate { get; set; }

        /// <summary>UTC timestamp of the last update, or null if never updated.</summary>
        [Description("UTC timestamp of the last update. Null if the contact has never been updated.")]
        public DateTime? UpdatedDate { get; set; }
    }
}
