using System.ComponentModel;

namespace ContactSystem.DTOs
{
    /// <summary>Group record returned by the API.</summary>
    public class GroupResponseDto
    {
        /// <summary>Primary key of the group.</summary>
        [Description("Primary key of the group (auto-generated by the server).")]
        public int GroupId { get; set; }

        /// <summary>Human-readable name of the group.</summary>
        [Description("Group name (1-255 characters).")]
        public string GroupName { get; set; } = string.Empty;

        /// <summary>Id of the project this group belongs to.</summary>
        [Description("Id of the project this group belongs to. A project can have at most one group.")]
        public int ProjectId { get; set; }
    }
}
