using System.ComponentModel;

namespace ContactSystem.DTOs
{
    public class GroupResponseDto
    {
        [Description("Primary key of the group (auto-generated by the server).")]
        public int GroupId { get; set; }

        [Description("Group name (1-255 characters).")]
        public string GroupName { get; set; } = string.Empty;

        [Description("Id of the project this group belongs to. A project can have many groups.")]
        public int ProjectId { get; set; }
    }
}
