using System.ComponentModel;

namespace ContactSystem.DTOs
{
    /// <summary>Project record returned by the API.</summary>
    public class ProjectResponseDto
    {
        /// <summary>Primary key of the project.</summary>
        [Description("Primary key of the project (auto-generated by the server).")]
        public int ProjectId { get; set; }

        /// <summary>Human-readable name of the project.</summary>
        [Description("Project name (1-255 characters).")]
        public string ProjectName { get; set; } = string.Empty;
    }
}
